# Base data directory (shared drive)
data_dir: '/Users/mbraaksma/Library/CloudStorage/GoogleDrive-braak014@umn.edu/Shared drives/NatCapTEEMs/Projects/Global GEP/Ecosystem Services SubFolders/Recreation/data/gep_recreation'
# data_dir: 's3://Files/base_data/gep_recreation'

# Input raster relative paths under data_dir
inputs:
  lulc:
    cropland: '0_processed_raster_inputs/lulc/lulc_esa_seals7_2010_1km_cropland_share.tif'
    forest: '0_processed_raster_inputs/lulc/lulc_esa_seals7_2010_1km_forest_share.tif'
    grassland: '0_processed_raster_inputs/lulc/lulc_esa_seals7_2010_1km_grassland_share.tif'
    othernat: '0_processed_raster_inputs/lulc/lulc_esa_seals7_2010_1km_othernat_share.tif'
    urban: '0_processed_raster_inputs/lulc/lulc_esa_seals7_2010_1km_urban_share.tif'
    water: '0_processed_raster_inputs/lulc/lulc_esa_seals7_2010_1km_water_share.tif'
  pa:
    wdpa: '0_processed_raster_inputs/pa/wdpa_share_1km.tif'
    kba: '0_processed_raster_inputs/pa/kba_share_1km.tif'
  road: '0_processed_raster_inputs/grip4_road_length/grip4_road_length_1km.tif'
  pop: '0_processed_raster_inputs/worldpop/ppp_2010_1km_aligned.tif'
  admin_borders: '0_inputs/gadm_410-levels.gpkg'
  tourism: 
    overnight_stays: '0_inputs/unwto-all-data-download_2022.xlsx'
    accommodation_locations: '0_inputs/Export_GEO-data_4-University-of-Minnesota.xlsx'


# Output raster relative paths under data_dir
estimap:
  ebp: '1_estimap/eb-p_1km.tif'
  human_inputs: '1_estimap/human_inputs_1km.tif'
  ros: '1_estimap/ros_1km.tif'
  high_quality: '1_estimap/high_quality_1km.tif'
  distance_to_hq: '1_estimap/distance_to_hq_1km.tif'
daily_rec:
  visits: '2_daily_rec/daily_rec_visits_1km.tif'
  value: '2_daily_rec/daily_rec_value_1km.tif'
  value_per_capita: '2_daily_rec/daily_rec_value_per_capita_1km.tif'
nbt:
  nights: '2_nbt/nbt_nights.gpkg'
  value: '2_nbt/nbt_value.gpkg'
  nights_per_capita: '2_nbt/nbt_value_per_capita.gpkg'
  accommodation_zones: '2_nbt/nbt_accommodation_zones.gpkg'  # Diagnostic output

# Conda (mamba) env
conda: 'envs/geo.yaml'

# Scoring parameters
scores:
  # EB-P
  lulc:
    cropland: 0.4
    forest: 1.0
    grassland: 0.7
    othernat: 0.85
    water: 1.0
    urban: 0.05
    other: 0.0
  pa_score: 1.0
  kba_score: 0.8
  ebp_classify:
    high: 1.5
    med_high: 1.0
    med_low: 0.5
    low: 0
  # Human Input
  urban_classify:
    high: 0.9
    med_high: 0.5
    med: 0.1
    med_low: 0.001
    low: 0
  road_classify:
    high: 100000
    med_high: 33819
    med: 13326
    med_low: 5453
    low: 0
  urban_road_matrix:
    - [1, 1, 2, 3, 4]
    - [1, 1, 2, 3, 4]
    - [2, 2, 2, 4, 5]
    - [3, 3, 4, 5, 5]
    - [3, 4, 4, 5, 5]
  ros_matrix:
    - [1, 1, 4, 7]
    - [1, 4, 4, 7]
    - [2, 2, 8, 8]
    - [3, 5, 5, 9]
    - [3, 6, 6, 9]


# NODATA value for outputs
nodata: -1